# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
