# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0003_auto_20170425_1045'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='LoginReg.User'),
            preserve_default=False,
        ),
    ]
