# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0003_auto_20170425_1045'),
        ('travel', '0002_trip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginReg.User')),
            ],
        ),
    ]
