# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0003_auto_20170425_1045'),
        ('travel', '0003_jointrip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jointrip',
            unique_together=set([('user', 'trip')]),
        ),
    ]
